export const BUILD_SETTLEMENT = 'BUILD_SETTLEMENT'
export const BUILD_CITY = 'BUILD_CITY'
export const FETCH_ALL_GAMES = 'FETCH_ALL_GAMES'
export const CREATE_GAME = 'CREATE_GAME'
export const END_GAME = 'END_GAME'
export const SET_PLAYER = 'SET_PLAYER'