export const BUILD_SETTLEMENT = 'BUILD_SETTLEMENT'
export const BUILD_CITY = 'BUILD_CITY'
export const FETCH_ALL_GAMES = 'FETCH_ALL_GAMES'
export const FETCH_ONE_GAME = 'FETCH_ONE_GAME'
export const CREATE_GAME = 'CREATE_GAME'
export const END_GAME = 'END_GAME'
export const SET_PLAYER = 'SET_PLAYER'
export const SET_USER = 'SET_USER'
export const END_TURN = 'END_TURN'

export const GET_TILES = 'GET_TILES'
export const SET_ROBBER = 'SET_ROBBER'

export const GET_INTERSECTIONS = 'GET_INTERSECTIONS'
export const SET_INTERSECTION = 'SET_INTERSECTION'
